### PR TITLE
Updated PR for new version of markitup gem.

### PR DESCRIPTION
**Pull request by wilatkabam**
Updated PR for gem release.

### CODE REVIEW

**Comment by FangAtKabam** [comment]
LGTM

**Comment by jaygeeseman** [comment]
Looks good

**Comment by wilatkabam** [comment]
@FangAtKabam @jaygeeseman Should I force push this to master? Master has a bunch of commits that were not included here, and that we no longer need. I'm wondering whether we should do that versus editing/removing the files manually.

**Comment by jaygeeseman** [comment]
It's probably best to add a commit to undo the changes in master first, then there's no need to force anything.

**Pull request closed without merging**
